### ISSUE TITLE
Lang Pack

### ISSUE THREAD

**Issue by bbilginn** [PaulFreund/Chat#1]
Hi, I would like to make Turkish translation.   How I can help you?

**Comment by PaulFreund** [comment]
Hi :) Great !

The translations are located in Chat/Strings/##/Resources.resw where ## is the language code. To add a new language you have to add a new folder to the Strings folder ( called tr for turkish ) with a Resources.resw file in it. I suggest copying the en folder and replacing the strings with turkish ones. 

If you don't have Win8 / VS2012 and can't edit the project you can also edit a copy of the english Resources.resw manually (its just XML) and upload the file afterwards so I can include it. 

Your help is highly appreciated! Thanks

**Comment by bbilginn** [comment]
Thanks :+1: 
I took the fork. I giving notice to merge.
